[project]
name = "dtml-delta-client"
version = "0"  # Do not change - managed by CI
description = "Delta Table Client"
authors = [
    {name = "MLE", email = "mlengineering@datamole.ai"}
]
classifiers = ["Private :: Do Not Upload"] # Prevents accidental uploads to PyPI.
requires-python = ">=3.11,<3.14"
dependencies = [
    "azure-identity>=1.17.1",
    "polars[deltalake,pyarrow]>=1.14.0,<2.0.0"
]


[dependency-groups]
dev = [
    "pytest~=8.4",
    "pytest-mock~=3.8",
    "ruff~=0.11",
]

[[tool.uv.index]]
name = "dtml"
url = "https://datamole.jfrog.io/artifactory/api/pypi/pypi-general/simple"
publish-url = "https://datamole.jfrog.io/artifactory/api/pypi/pypi-general-local"
explicit = true

[tool.ruff]
line-length = 79
target-version = "py312"
lint.select = [
    "E",
    "F",
    "N",
    "W",
    "I001",
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]
"*/**" = ["E402"]

[tool.hatch.build.targets.wheel]
packages = ["dtml"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
