name: Publish

on:
  push:
    branches: [main]


jobs:
  publish_package:
    env:
      CHANGELOG_FILE: CHANGELOG.md
      FULL_CHANGELOG_FILE: FULL_CHANGELOG.md
      PACKAGE_NAME: dtml-delta-client
      PACKAGE_PATH: dtml
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write
    concurrency:
      group: publish-package
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.7.11
      - name: Install convco
        env:
          CONVCO_VERSION: v0.6.2
        run: |
          curl -sSfL "https://github.com/convco/convco/releases/download/${{ env.CONVCO_VERSION }}/convco-ubuntu.zip" | zcat > /usr/local/bin/convco
          chmod +x /usr/local/bin/convco
      - name: Set variables
        run: |
          base_version_command="
            convco
            version
            --prefix=${{ env.PACKAGE_NAME }}
            --paths=${{ env.PACKAGE_PATH }}/
          "
          old_version=$($base_version_command)
          if [ $old_version = "0.0.0" ]; then # i.e. there is no version yet
            new_version="0.1.0"
          else
            new_version=$($base_version_command --bump)
          fi
          new_tag="v$new_version"
          package_path=${{ env.PACKAGE_PATH }}
          echo "OLD_VERSION=$old_version" >> $GITHUB_ENV
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV
          echo "PACKAGE_PATH=$package_path" >> $GITHUB_ENV
          echo "old version: $old_version"
          echo "new version: $new_version"
          echo "new tag: $new_tag"
          echo "packages path: $package_path"
      - name: Release and publish
        if: ${{ env.OLD_VERSION != env.NEW_VERSION }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ########################################
          # Generate changelogs
          ########################################
          base_changelog_command="
            convco
            changelog
            --prefix=${{ env.PACKAGE_NAME }}/
            --paths=${{ env.PACKAGE_PATH }}/
            --unreleased=${{ env.NEW_TAG }}
          "
          $base_changelog_command --max-versions=1 > ${{ env.CHANGELOG_FILE }}
          $base_changelog_command > ${{ env.FULL_CHANGELOG_FILE }}
          ########################################
          # Create GitHub Release
          ########################################
          gh release create \
            ${{ env.NEW_TAG }} \
            --title ${{ env.NEW_TAG }} \
            --notes-file ${{ env.CHANGELOG_FILE }} \
            ${{ env.FULL_CHANGELOG_FILE }}
          ########################################
          # Publish to JFrog
          ########################################
          # Version set based on tag using hatch-vcs
          uv build
          uv publish \
            --index dtml \
            --username ${{ secrets.JFROG_PUBLISH_USERNAME }} \
            --password ${{ secrets.JFROG_PUBLISH_PASSWORD }}
